name: loon-basic-deployment

services:
  loon:
    build:
      context: ../..
      dockerfile: build/package/Dockerfile
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yaml:ro
  caddy:
    build:
      context: .
      dockerfile: caddy.dockerfile
    restart: unless-stopped
    env_file:
      - caddy.env
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
